config/routes.rb
Rails.application.routes.draw do

  root :to => 'projects#index'
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :projects, :users, :sessions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :project
  validates_presence :investor_id, :amount
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  validates_presence_of :user, :title, :description, :found_necessary
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :user_profile
  has_many :projects
  has_many :investments

  validates_presence_of :email, :password
  validates_uniqueness_of :email
  
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user

  validates_presence_of :bio, :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to root_url, notice: "Thank you for signing up!"
  else
    render "new"
  end
end

  def login
  end

  def edit
  end

  def update
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfunding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">CoolCrowdFunding</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="<%= projects_path %>">Projects</a>
        <a class="p-2 text-dark" href="#">Enterprise</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">Pricing</a>
      </nav>
      <p>
        <small>
          <% if current_user %>
            Logged in as <%= current_user.email %>.
            <%= link_to "Log Out", logout_path, class: "btn btn-outline-primary" %>
          <% else %>
            <%= link_to "Sign Up", signup_path, class: "btn btn-outline-primary"%> or
            <%= link_to "Log In", login_path , class: "btn btn-outline-primary" %>
          <% end %>
        </small>
      </p>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/delete.html.erb
<h1>Projects#delete</h1>
<p>Find me in app/views/projects/delete.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Projects</h1>
      <p>some projects finding investors.</p>
    </div>
  </div>
</div>


<div class="container">
  <div class="card-deck text-center">

    <div class="container">
      <% @projects.each_slice(3)  do |projects| %>
        <div class="row">
          <% projects.each  do |project| %>
            <div class="col-sm-6 col-lg-4 col-md-4">
              <div class="card shadow-sm mt-2">
                <div class="card-header">
                    <h5> <%= project.title %> </h5>
                </div>
                <div class="card-body">
                  <h6> <%= project.created_at.strftime('%b %d, %Y') %> </h6>
                  <p> <%= raw(project.description).truncate(300) %> </p>
                  <p>  <%= link_to "details", project_path(project) %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/projects/show.html.erb
<%= @project.inspect %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/new.html.erb
<div class="row">

</div>


<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <h1>Sign Up</h1>
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="actions">
          <p><br><%= f.submit "Sign Up", class: 'btn btn-primary' %></p>
        </div>
      <% end %>

    </div>
    <div class="col-md-4"></div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>